In [1]:
from constructor import Constructor
from models import Data 

In [2]:
import tensorflow as tf
import numpy as np
import os 

In [3]:
Data = Data([1,1,1],30000,0.01)

In [4]:
Data.getData()

In [5]:
num_time_steps = 20
batch_size = 32
start_id = 3000

In [6]:
reshaped_x_test = tf.reshape(Data.x_test,[1,7*50,3])
reshaped_y_test = tf.reshape(Data.y_test,[1,7*50,3])

In [7]:
checkpoint_dir = './training_checkpoints'
os.path.join(checkpoint_dir, "my_ckpt")

'./training_checkpoints/my_ckpt'

In [8]:
model2 = Constructor(Data,64,15,baseline=False)

In [9]:
model2.model.predict(reshaped_x_test)

array([[[-0.07021957, -0.09285274,  0.17173232],
        [-0.06060585, -0.0878488 ,  0.10749836],
        [-0.04705337, -0.0838411 ,  0.0162568 ],
        ...,
        [ 0.03067562,  0.23035063, -0.4155896 ],
        [ 0.04116188,  0.23983665, -0.3994311 ],
        [ 0.05226354,  0.25020537, -0.38301754]]], dtype=float32)

In [10]:
reshaped_y_test

<tf.Tensor: shape=(1, 350, 3), dtype=float64, numpy=
array([[[-0.07234471, -0.14103419, -0.23514842],
        [-0.07958619, -0.15584822, -0.22645068],
        [-0.08762288, -0.17223056, -0.21746566],
        ...,
        [ 0.03658101,  0.14253521, -0.41906814],
        [ 0.04710261,  0.15181248, -0.40519115],
        [ 0.05756852,  0.16240045, -0.39119531]]])>

In [11]:
listen = tf.reshape(tf.convert_to_tensor(
    np.array([Data.datapoints[50*32+3000:80*32+3000]])
),
[1,30*32,3])

In [15]:
model2.Data.prediction_x_data

<tf.Tensor: shape=(150, 1, 3), dtype=float64, numpy=
array([[[ 4.65114646e-02,  6.25761633e-01,  1.77567483e+01]],

       [[ 1.01661950e-01,  6.27332058e-01,  1.72899541e+01]],

       [[ 1.52007309e-01,  6.34956979e-01,  1.68357744e+01]],

       [[ 1.98576593e-01,  6.48551873e-01,  1.63938658e+01]],

       [[ 2.42294799e-01,  6.68073284e-01,  1.59639072e+01]],

       [[ 2.83997077e-01,  6.93526740e-01,  1.55455980e+01]],

       [[ 3.24442259e-01,  7.24973055e-01,  1.51386573e+01]],

       [[ 3.64325639e-01,  7.62533503e-01,  1.47428230e+01]],

       [[ 4.04290989e-01,  8.06394268e-01,  1.43578518e+01]],

       [[ 4.44941847e-01,  8.56810516e-01,  1.39835200e+01]],

       [[ 4.86852090e-01,  9.14110357e-01,  1.36196245e+01]],

       [[ 5.30575904e-01,  9.78698947e-01,  1.32659843e+01]],

       [[ 5.76657197e-01,  1.05106291e+00,  1.29224430e+01]],

       [[ 6.25638563e-01,  1.13177525e+00,  1.25888713e+01]],

       [[ 6.78069889e-01,  1.22150089e+00,  1.22651710e+01]],

  

In [12]:
model2.Data.prediction_y_data

<tf.Tensor: shape=(150, 1, 3), dtype=float64, numpy=
array([[[ 5.51504858e-02,  1.57042514e-03, -4.66794258e-01]],

       [[ 5.03453590e-02,  7.62492077e-03, -4.54179634e-01]],

       [[ 4.65692838e-02,  1.35948935e-02, -4.41908602e-01]],

       [[ 4.37182058e-02,  1.95214108e-02, -4.29958655e-01]],

       [[ 4.17022781e-02,  2.54534566e-02, -4.18309171e-01]],

       [[ 4.04451823e-02,  3.14463152e-02, -4.06940703e-01]],

       [[ 3.98833792e-02,  3.75604478e-02, -3.95834354e-01]],

       [[ 3.99653509e-02,  4.38607653e-02, -3.84971201e-01]],

       [[ 4.06508572e-02,  5.04162476e-02, -3.74331769e-01]],

       [[ 4.19102431e-02,  5.72998410e-02, -3.63895492e-01]],

       [[ 4.37238145e-02,  6.45885897e-02, -3.53640164e-01]],

       [[ 4.60812932e-02,  7.23639633e-02, -3.43541350e-01]],

       [[ 4.89813658e-02,  8.07123415e-02, -3.33571711e-01]],

       [[ 5.24313261e-02,  8.97256385e-02, -3.23700239e-01]],

       [[ 5.64468164e-02,  9.95020227e-02, -3.13891359e-01]],

  

In [16]:
model2.model(model2.Data.prediction_data_listen)

<tf.Tensor: shape=(1, 1000, 3), dtype=float32, numpy=
array([[[ 0.21623604, -0.04620479, -0.45305812],
        [ 0.16562642,  0.0508429 , -0.40415472],
        [ 0.13833928,  0.1271614 , -0.3630105 ],
        ...,
        [ 0.1120437 ,  0.11150111, -0.502596  ],
        [ 0.09660179,  0.1150731 , -0.4865462 ],
        [ 0.08348834,  0.11887057, -0.47098732]]], dtype=float32)>

In [17]:
for i in model2.Data.prediction_x_data:
    print(model2.model.predict(tf.expand_dims(i,axis=0)))

[[[ 0.07252662  0.12285973 -0.4558831 ]]]
[[[ 0.06355995  0.12703879 -0.44121405]]]
[[[ 0.05645879  0.13143297 -0.42697674]]]
[[[ 0.05112311  0.1360928  -0.41318157]]]
[[[ 0.04748033  0.14108922 -0.39984748]]]
[[[ 0.0454797   0.14651032 -0.38699663]]]
[[[ 0.04508275  0.15245189 -0.3746481 ]]]
[[[ 0.04625232  0.15901168 -0.36281177]]]
[[[ 0.04894077  0.1662813  -0.35148197]]]
[[[ 0.05308057  0.17433907 -0.34063423]]]
[[[ 0.05857934  0.18324943 -0.3302267 ]]]
[[[ 0.06532104  0.19306292 -0.32020518]]]
[[[ 0.07317191  0.2038237  -0.31051055]]]
[[[ 0.08198882  0.21557952 -0.30109128]]]
[[[ 0.09162638  0.22839464 -0.29191196]]]
[[[ 0.10194156  0.24235822 -0.28296235]]]
[[[ 0.11279213  0.25759682 -0.2742614 ]]]
[[[ 0.12403599  0.27427623 -0.26585868]]]
[[[ 0.13553128  0.29260036 -0.25782382]]]
[[[ 0.1471462   0.31279394 -0.2502265 ]]]
[[[ 0.15878299  0.335076   -0.2430994 ]]]
[[[ 0.17041433  0.3596141  -0.23638786]]]
[[[ 0.18212281  0.38647845 -0.2298996 ]]]
[[[ 0.19412151  0.415609   -0.2232