In [6]:
from constructor import Constructor
from models import Data 

In [7]:
import tensorflow as tf
import numpy as np
import os 

In [8]:
Data = Data([1,1,1],30000,0.01)

In [9]:
Data.getData()

In [10]:
model1 = Constructor(Data,64,25)
model1.fitModel()

Epoch 1/25
25/25 [==============================] - 4s 99ms/step - loss: 0.4637 - accuracy: 0.2545 - val_loss: 0.2005 - val_accuracy: 0.6743

Epoch 00001: saving model to training_checkpoints/64LSTM_Neurons25Epochs.ckpt
Epoch 2/25
25/25 [==============================] - 2s 72ms/step - loss: 0.1853 - accuracy: 0.5816 - val_loss: 0.0998 - val_accuracy: 0.6543

Epoch 00002: saving model to training_checkpoints/64LSTM_Neurons25Epochs.ckpt
Epoch 3/25
25/25 [==============================] - 2s 71ms/step - loss: 0.0978 - accuracy: 0.7205 - val_loss: 0.0637 - val_accuracy: 0.7657

Epoch 00003: saving model to training_checkpoints/64LSTM_Neurons25Epochs.ckpt
Epoch 4/25
25/25 [==============================] - 2s 70ms/step - loss: 0.0622 - accuracy: 0.8405 - val_loss: 0.0476 - val_accuracy: 0.8029

Epoch 00004: saving model to training_checkpoints/64LSTM_Neurons25Epochs.ckpt
Epoch 5/25
25/25 [==============================] - 2s 83ms/step - loss: 0.0462 - accuracy: 0.8497 - val_loss: 0.0389 - 

In [11]:
model2 = Constructor(Data,64,25,baseline=False)

In [12]:
listen = tf.reshape(tf.convert_to_tensor(
    np.array([Data.datapoints[50*32+3000:80*32+3000]])
),
[1,30*32,3])

In [14]:
model2.Data.prediction_y_data

<tf.Tensor: shape=(150, 1, 3), dtype=float64, numpy=
array([[[ 5.51504858e-02,  1.57042514e-03, -4.66794258e-01]],

       [[ 5.03453590e-02,  7.62492077e-03, -4.54179634e-01]],

       [[ 4.65692838e-02,  1.35948935e-02, -4.41908602e-01]],

       [[ 4.37182058e-02,  1.95214108e-02, -4.29958655e-01]],

       [[ 4.17022781e-02,  2.54534566e-02, -4.18309171e-01]],

       [[ 4.04451823e-02,  3.14463152e-02, -4.06940703e-01]],

       [[ 3.98833792e-02,  3.75604478e-02, -3.95834354e-01]],

       [[ 3.99653509e-02,  4.38607653e-02, -3.84971201e-01]],

       [[ 4.06508572e-02,  5.04162476e-02, -3.74331769e-01]],

       [[ 4.19102431e-02,  5.72998410e-02, -3.63895492e-01]],

       [[ 4.37238145e-02,  6.45885897e-02, -3.53640164e-01]],

       [[ 4.60812932e-02,  7.23639633e-02, -3.43541350e-01]],

       [[ 4.89813658e-02,  8.07123415e-02, -3.33571711e-01]],

       [[ 5.24313261e-02,  8.97256385e-02, -3.23700239e-01]],

       [[ 5.64468164e-02,  9.95020227e-02, -3.13891359e-01]],

  

In [15]:
model2.model(model2.Data.prediction_data_listen)

<tf.Tensor: shape=(1, 1000, 3), dtype=float32, numpy=
array([[[ 0.1496348 ,  0.00496594, -0.22251475],
        [ 0.16292422,  0.05888693, -0.3413963 ],
        [ 0.13811973,  0.11742463, -0.39448604],
        ...,
        [ 0.09371194, -0.04543688, -0.5035262 ],
        [ 0.08365622, -0.03592911, -0.49237716],
        [ 0.07474874, -0.02629855, -0.48149702]]], dtype=float32)>

In [16]:
for i in model2.Data.prediction_x_data:
    print(model2.model.predict(tf.expand_dims(i,axis=0)))

[[[ 0.06692274 -0.01660077 -0.47080126]]]
[[[ 0.06013013 -0.00688548 -0.46023706]]]
[[[ 0.05433517  0.00280405 -0.44977722]]]
[[[ 0.04950872  0.01243249 -0.4394167 ]]]
[[[ 0.04562721  0.02197538 -0.42916745]]]
[[[ 0.0426706   0.0314194  -0.41905442]]]
[[[ 0.04062158  0.0407633  -0.40911034]]]
[[[ 0.03946623  0.05001869 -0.3993735 ]]]
[[[ 0.03919306  0.05920847 -0.38988346]]]
[[[ 0.03979425  0.06836746 -0.38067803]]]
[[[ 0.04126471  0.07754155 -0.37179187]]]
[[[ 0.04360314  0.08678698 -0.36325297]]]
[[[ 0.04681098  0.09616979 -0.35508126]]]
[[[ 0.05089273  0.10576633 -0.34728634]]]
[[[ 0.05585565  0.11566161 -0.3398656 ]]]
[[[ 0.06170957  0.12595041 -0.33280194]]]
[[[ 0.06846626  0.13673738 -0.32606068]]]
[[[ 0.07613939  0.14813669 -0.31958792]]]
[[[ 0.08474426  0.16027325 -0.31330666]]]
[[[ 0.09429763  0.1732831  -0.30711362]]]
[[[ 0.10481861  0.18731488 -0.3008746 ]]]
[[[ 0.11632983  0.20253131 -0.29442033]]]
[[[ 0.1288597   0.21911141 -0.28754103]]]
[[[ 0.14244649  0.23725258 -0.2799